# constants used by the jaide emulator.
# josiah bergen, january 2026


# mnemonics
OP_HALT = 0
OP_LOAD = 1
OP_STORE = 2
OP_MOVE = 3
OP_PUSH = 4
OP_POP = 5
OP_ADD = 6
OP_ADC = 7
OP_SUB = 8
OP_SBB = 9
OP_INC = 10
OP_DEC = 11
OP_SHL = 12
OP_SHR = 13
OP_AND = 14
OP_OR = 15
OP_NOR = 16
OP_NOT = 17
OP_XOR = 18
OP_INB = 19
OP_OUTB = 20
OP_CMP = 21
OP_JUMP = 22
OP_JZ = 23
OP_JNZ = 24
OP_JC = 25
OP_JNC = 26
OP_CALL = 27
OP_RET = 28
OP_INT = 29
OP_IRET = 30
OP_NOP = 31

MNEMONICS: dict[int, str] = {
    OP_HALT: "HALT",
    OP_LOAD: "LOAD",
    OP_STORE: "STORE",
    OP_MOVE: "MOV",
    OP_PUSH: "PUSH",
    OP_POP: "POP",
    OP_ADD: "ADD",
    OP_ADC: "ADC",
    OP_SUB: "SUB",
    OP_SBB: "SBB",
    OP_INC: "INC",
    OP_DEC: "DEC",
    OP_SHL: "LSH",
    OP_SHR: "RSH",
    OP_AND: "AND",
    OP_OR: "OR",
    OP_NOR: "NOR",
    OP_NOT: "NOT",
    OP_XOR: "XOR",  
    OP_INB: "INB",
    OP_OUTB: "OUTB",
    OP_CMP: "CMP",
    OP_JUMP: "JMP",
    OP_JZ: "JZ",
    OP_JNZ: "JNZ",
    OP_JC: "JC",
    OP_JNC: "JNC",
    OP_CALL: "CALL",
    OP_RET: "RET",
    OP_INT: "INT",
    OP_IRET: "IRET",
    OP_NOP: "NOP",
}

# addressing modes
MODE_REG = 0
MODE_IMM16 = 1
MODE_MEM_DIRECT = 2
MODE_MEM_INDIRECT = 3

ADDRESSING_MODE_TO_SIZE = {
    MODE_REG: 2,
    MODE_IMM16: 4,
    MODE_MEM_DIRECT: 4,
    MODE_MEM_INDIRECT: 2,
}

ADDRESSING_MODE_TO_STRING = {
    MODE_REG: "REG",
    MODE_IMM16: "IMM16",
    MODE_MEM_DIRECT: "[IMM16]",
    MODE_MEM_INDIRECT: "[REG]",
}

OPCODE_TO_POSSIBLE_MODES = {
    OP_HALT: [],
    OP_LOAD: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_STORE: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_MOVE: [MODE_REG, MODE_IMM16],
    OP_PUSH: [MODE_REG, MODE_IMM16],
    OP_POP: [MODE_REG],
    OP_ADD: [MODE_REG, MODE_IMM16],
    OP_ADC: [MODE_REG, MODE_IMM16],
    OP_SUB: [MODE_REG, MODE_IMM16],
    OP_SBB: [MODE_REG, MODE_IMM16],
    OP_INC: [MODE_REG],
    OP_DEC: [MODE_REG],
    OP_SHL: [MODE_REG, MODE_IMM16],
    OP_SHR: [MODE_REG, MODE_IMM16],
    OP_AND: [MODE_REG, MODE_IMM16],
    OP_OR: [MODE_REG, MODE_IMM16],
    OP_NOR: [MODE_REG, MODE_IMM16],
    OP_NOT: [MODE_REG],
    OP_XOR: [MODE_REG, MODE_IMM16],
    OP_INB: [MODE_REG, MODE_IMM16],
    OP_OUTB: [MODE_REG, MODE_IMM16],
    OP_CMP: [MODE_REG, MODE_IMM16],
    OP_JUMP: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_JZ: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_JNZ: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_JC: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_JNC: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_CALL: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT],
    OP_RET: [],
    OP_INT: [MODE_MEM_DIRECT, MODE_MEM_INDIRECT], # Based on inst.txt line 123-124
    OP_IRET: [],
    OP_NOP: [],
}
