# constants.py
# constants used by the jaide emulator.
# josiah bergen, january 2026


# mnemonics
OP_LOAD = 0x0
OP_STORE = 0x1
OP_MOVE = 0x2
OP_PUSH = 0x3
OP_POP = 0x4
OP_ADD = 0x5
OP_ADC = 0x6
OP_SUB = 0x7
OP_SBB = 0x8
OP_INC = 0x9
OP_DEC = 0xA
OP_SHL = 0xB
OP_SHR = 0xC
OP_AND = 0xD
OP_OR = 0xE
OP_NOR = 0xF
OP_NOT = 0x10
OP_XOR = 0x11
OP_INB = 0x12
OP_OUTB = 0x13
OP_CMP = 0x14
OP_SEC = 0x15
OP_CLC = 0x16
OP_CLZ = 0x17
OP_JUMP = 0x18
OP_JZ = 0x19
OP_JNZ = 0x1A
OP_JC = 0x1B
OP_JNC = 0x1C
OP_INT = 0x1D
OP_HALT = 0x1E
OP_NOP = 0x1F

MNEMONICS: dict[int, str] = {
    OP_LOAD: "LOAD",
    OP_STORE: "STORE",
    OP_MOVE: "MOVE",
    OP_PUSH: "PUSH",
    OP_POP: "POP",
    OP_ADD: "ADD",
    OP_ADC: "ADC",
    OP_SUB: "SUB",
    OP_SBB: "SBB",
    OP_INC: "INC",
    OP_DEC: "DEC",
    OP_SHL: "SHL",
    OP_SHR: "SHR",
    OP_AND: "AND",
    OP_OR: "OR",
    OP_NOR: "NOR",
    OP_NOT: "NOT",
    OP_XOR: "XOR",  
    OP_INB: "INB",
    OP_OUTB: "OUTB",
    OP_CMP: "CMP",
    OP_SEC: "SEC",
    OP_CLC: "CLC",
    OP_CLZ: "CLZ",
    OP_JUMP: "JUMP",
    OP_JZ: "JZ",
    OP_JNZ: "JNZ",
    OP_JC: "JC",
    OP_JNC: "JNC",
    OP_INT: "INT",
    OP_HALT: "HALT",
    OP_NOP: "NOP",
}

# addressing modes
MODE_NO_OPERANDS = 0b000
MODE_REG = 0b001
MODE_IMM8 = 0b010 
MODE_REG_REG = 0b011 
MODE_REG_IMM8 = 0b100 
MODE_REG_IMM16 = 0b101 
MODE_REG_REGPAIR = 0b110
MODE_IMM16 = 0b111

ADDRESSING_MODE_TO_SIZE = {
    MODE_NO_OPERANDS: 1,
    MODE_REG: 2,
    MODE_IMM8: 3,
    MODE_REG_REG: 2,
    MODE_REG_IMM8: 3,
    MODE_REG_IMM16: 4,
    MODE_REG_REGPAIR: 4,
    MODE_IMM16: 4,
}

ADDRESSING_MODE_TO_STRING = {
    MODE_NO_OPERANDS: "no operands",
    MODE_REG: "RG--",
    MODE_IMM8: "---- IMM8",
    MODE_REG_REG: "RGRG",
    MODE_REG_IMM8: "RG-- IMM8",
    MODE_REG_IMM16: "RG-- 16LO 16HI",
    MODE_REG_REGPAIR: "RG-- RGRG",
    MODE_IMM16: "---- 16LO IMHI",
}

OPCODE_TO_POSSIBLE_MODES = {
    OP_LOAD:  [MODE_REG_IMM16, MODE_REG_REGPAIR],
    OP_STORE: [MODE_REG_IMM16, MODE_REG_REGPAIR],
    OP_MOVE:  [MODE_REG_REG,   MODE_REG_IMM8],
    OP_PUSH:  [MODE_REG,       MODE_IMM8],
    OP_POP:   [MODE_REG],
    OP_ADD:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_ADC:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_SUB:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_SBB:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_INC:   [MODE_REG],
    OP_DEC:   [MODE_REG],
    OP_SHL:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_SHR:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_AND:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_OR:    [MODE_REG_REG,   MODE_REG_IMM8],
    OP_NOR:   [MODE_REG_REG,   MODE_REG_IMM8],
    OP_NOT:   [MODE_REG],
    OP_XOR:   [MODE_REG_REG,    MODE_REG_IMM8],
    OP_INB:   [MODE_REG_REG,    MODE_REG_IMM8],
    OP_OUTB:  [MODE_REG_REG,    MODE_REG_IMM8],
    OP_CMP:   [MODE_REG_REG,    MODE_REG_IMM8],
    OP_SEC:   [MODE_NO_OPERANDS],
    OP_CLC:   [MODE_NO_OPERANDS],
    OP_CLZ:   [MODE_NO_OPERANDS],
    OP_JUMP:  [MODE_IMM16],
    OP_JZ:    [MODE_IMM16],
    OP_JNZ:   [MODE_IMM16],
    OP_JC:    [MODE_IMM16],
    OP_JNC:   [MODE_IMM16],
    OP_INT:   [MODE_IMM8],
    OP_HALT:  [MODE_NO_OPERANDS],
    OP_NOP:   [MODE_NO_OPERANDS],
}